# Generated by Django 3.2.5 on 2021-10-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
